[package]
name = "tungstenite"
description = "Lightweight stream-based WebSocket implementation"
categories = ["web-programming::websocket", "network-programming"]
keywords = ["websocket", "io", "web"]
authors = ["Alexey Galakhov"]
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://github.com/snapview/tungstenite-rs"
documentation = "https://docs.rs/tungstenite/0.10.1"
repository = "https://github.com/snapview/tungstenite-rs"
version = "0.10.1"
edition = "2018"

[features]
default = ["tls"]
tls = ["native-tls"]
rusttls-tls = ["rustls"]

[dependencies]
base64 = "0.12.0"
byteorder = "1.3.2"
bytes = "0.5"
http = "0.2"
httparse = "1.3.4"
input_buffer = "0.3.0"
log = "0.4.8"
rand = "0.7.2"
sha-1 = "0.8.1"
url = "2.1.0"
utf-8 = "0.7.5"

[dependencies.native-tls]
optional = true
version = "0.2.3"

[dependencies.rustls]
optional = true
version = "0.17.0"

[dev-dependencies]
env_logger = "0.7.1"
net2 = "0.2.33"
